sandbox:
  tcp-port: 9092
  db-url: jdbc:h2:mem:coffeedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  username: coffee
  password: coffee123@

spring:
  datasource:
    url: jdbc:h2:tcp://localhost:${sandbox.tcp-port}/mem:coffeedb
    username: ${sandbox.username}
    password: ${sandbox.password}

  liquibase:
    contexts: h2


  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
